FROM ubuntu:20.04

RUN apt-get update -y && \
    apt-get install -y unzip wget qemu-system-aarch64 && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists

ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN groupadd --gid 1000 runuser && \
    useradd --home-dir /home/runuser --shell /bin/bash --uid 1000 --gid 1000 runuser


RUN mkdir /alu_emu && \
    chown -R runuser:runuser /alu_emu
WORKDIR /alu_emu
USER 1000:1000

RUN wget -nv https://github.com/gm2552/alu-qemu-dev/raw/master/cloud.img && \
    wget -nv https://github.com/gm2552/alu-qemu-dev/raw/master/flash0.img.zip && \
    wget -nv https://github.com/gm2552/alu-qemu-dev/raw/master/flash1.img.zip && \
    wget -nv https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-arm64-uefi1.img && \
    unzip flash0.img.zip && \
    unzip flash1.img.zip && \
    ls -la
